version: '3.1'
services:
  app:
    container_name: moebooru_app
    build:
      context: .
      dockerfile: Dockerfile
    image: moebooru/moebooru
    command: bundle exec rails s -b 0.0.0.0 -p 5000
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    links:
     - postgres
    volumes:
      - './config/local_config.rb:/app/config/local_config.rb'
      - './config/database.yml:/app/config/database.yml'
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - 'pg:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: moebooru_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imouto
      PGDATA: '/var/lib/postgresql/data'
    ports:
      - "5432:5432"
volumes:
  pg:
